name: CI

on: [push, pull_request]

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:7.2
      options: --privileged

    steps:
    - uses: actions/checkout@v3

    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: Pomodoro.flatpak
        manifest-path: com.github.oowoosh0.pomodoro.yml
        run-tests: true
        repository-name: appcenter
        repository-url: https://flatpak.elementary.io/repo.flatpakrepo
        cache-key: "flatpak-builder-${{ github.sha }}"

  lint:
    name: Lint
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint
        run: io.elementary.vala-lint -d .
